# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code into the container
COPY . .

# Expose the port that the app will run on
EXPOSE 8000

# Start the app using uvicorn as the server
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

